apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-deployment
  namespace: api
  labels:
    app: todos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todos
  template:
    metadata:
      labels:
        app: todos
    spec:
      containers:
      - name: todos
        image: todos
        imagePullPolicy: Never
        ports:
          - containerPort: 8080
