apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todos-ingress
  namespace: api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: todos.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: todos-service
                port:
                  number: 80
          - path: /prometheus
            pathType: Prefix
            backend:
              service:
                name: todos-prometheus-grafana
                port:
                  number: 80
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: todos-grafana
                port:
                  number: 80
