apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-nfs-pv
  namespace: default
  labels:
    app: postgres
    type: nfs-storage
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  nfs:
    server: 192.168.0.191
    path: /srv/nfs4/postgres/data
