apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-nfs-pvc
  namespace: default
  labels:
    app: postgres
    type: nfs-storage
spec:
  selector:
    matchLabels:
      type: nfs-storage
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
